#deployment do mongo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
---
#SERVICE MONGODB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  type: ClusterIP

---
#deployment da api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: typhanael/rotten-potatoes:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd
---   
#SERVICE API
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      target: 5000
      nodePort: 30000
  type: NodePort

