name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Docbker Build and Push
        uses: docker/build-push@v2.7.0
        with:
          context: ./code
          file: ./code/Dockerfile
          push: true
          tags: |
            typhanael/rotten-potatoes:latest
            typhanael/rotten-potatoes:${{ github.run_number }}
            
